### ISSUE TITLE
Project scheduled trigger doesn't have destination_environment_id populated

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusSolutionsEngineering/OctopusTerraformExport#25]
### Octopus version

2024.2.6366

### Octoterra version

latest

### What happened

This is the tf generated for a project trigger

```resource "octopusdeploy_project_scheduled_trigger" "projecttrigger_octopub___audits___yaml_deploy_to_development__apac_" {
  space_id    = "${trimspace(var.octopus_space_id)}"
  name        = "Deploy to Development (APAC)"
  description = ""
  timezone    = "E. Australia Standard Time"
  is_disabled = true
  project_id  = "${octopusdeploy_project.project_octopub___audits___yaml.id}"
  tenant_ids  = []

  deploy_new_release_action {
    destination_environment_id = ""
  }

  once_daily_schedule {
    start_time   = "2024-04-29T06:15:00"
    days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
  }
}
```

### Octoterra log output

n/a

### Reproduction steps

Runbook that generated the tf: https://demo.octopus.app/app#/Spaces-178/projects/octopub-yaml-serializer/operations/runbooks/Runbooks-7736/overview

**Comment by mcasperson** [comment]
This was fixed with https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/issues/24.

Note however projects with scheduled triggers that reference a channel will need a new channel created in the project. This is because there is no way to lookup the default channel created with a new project. See the discussion [here](https://octopusdeploy.slack.com/archives/C056NSRCRAL/p1714339367747849) for more details.
